/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DonRouteImport } from './routes/don'
import { Route as MecenatEntrepriseRouteImport } from './routes/mecenat-entreprise'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DonRoute = DonRouteImport.update({
  id: '/don',
  path: '/don',
  getParentRoute: () => rootRouteImport,
} as any)
const MecenatEntrepriseRoute = MecenatEntrepriseRouteImport.update({
  id: '/mecenat-entreprise',
  path: '/mecenat-entreprise',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/don': typeof DonRoute
  '/mecenat-entreprise': typeof MecenatEntrepriseRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/don': typeof DonRoute
  '/mecenat-entreprise': typeof MecenatEntrepriseRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/don': typeof DonRoute
  '/mecenat-entreprise': typeof MecenatEntrepriseRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/don' | '/mecenat-entreprise' | '/mentions-legales' | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/don' | '/mecenat-entreprise' | '/mentions-legales' | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/don'
    | '/mecenat-entreprise'
    | '/mentions-legales'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DonRoute: typeof DonRoute
  MecenatEntrepriseRoute: typeof MecenatEntrepriseRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/don': {
      id: '/don'
      path: '/don'
      fullPath: '/don'
      preLoaderRoute: typeof DonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mecenat-entreprise': {
      id: '/mecenat-entreprise'
      path: '/mecenat-entreprise'
      fullPath: '/mecenat-entreprise'
      preLoaderRoute: typeof MecenatEntrepriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DonRoute: DonRoute,
  MecenatEntrepriseRoute: MecenatEntrepriseRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
